# -*- coding: utf-8 -*-
"""
목업용 참조 데이터.
- RECIPES: hye1ns/datanalysis_recipe (만개의 레시피) recipe_main.csv 스키마를 따라 구조화.
  목업 단계에서는 재료를 {name, amount} 구조로 정규화해 저장. (실데이터 연결 시
  "김치 200g" 문자열 파싱 로직으로 대체 예정)
- NUTRIENTS: 재료별 영양소(100g 기준). 목업용 근사치.
- REFERENCE_INTAKE: 성인 1일 권장 섭취량(대략치).
"""

RECIPES = [
    {
        "index": 1, "title": "김치찌개", "type": "찌개",
        "situation": "일상", "ingredient_tag": "채소류", "method": "끓이기",
        "url": "https://www.10000recipe.com/recipe/list?q=김치찌개",
        "views": 980, "chef": "목업셰프", "servings": 3, "cook_time": 30, "difficulty": "초급",
        "ingredients": [
            {"name": "김치", "amount": "200g"}, {"name": "돼지고기", "amount": "150g"},
            {"name": "두부", "amount": "100g"}, {"name": "양파", "amount": "1/2개"},
            {"name": "대파", "amount": "1대"}, {"name": "마늘", "amount": "1큰술"},
            {"name": "고춧가루", "amount": "1큰술"},
        ],
        "intro": "익은 김치와 돼지고기로 끓이는 가장 기본이 되는 찌개입니다.",
        "steps": ["돼지고기를 볶다가 김치를 넣고 함께 볶는다", "물을 붓고 15분 끓인다", "두부·양파·대파를 넣고 5분 더 끓인다"],
        "tags": ["#김치", "#얼큰한찌개", "#밥도둑"],
        "rich": ["fiber", "protein"],
    },
    {
        "index": 2, "title": "된장찌개", "type": "찌개",
        "situation": "일상", "ingredient_tag": "채소류", "method": "끓이기",
        "url": "https://www.10000recipe.com/recipe/list?q=된장찌개",
        "views": 870, "chef": "목업셰프", "servings": 2, "cook_time": 25, "difficulty": "초급",
        "ingredients": [
            {"name": "된장", "amount": "2큰술"}, {"name": "두부", "amount": "100g"},
            {"name": "애호박", "amount": "1/2개"}, {"name": "양파", "amount": "1/2개"},
            {"name": "감자", "amount": "1개"}, {"name": "대파", "amount": "1대"},
        ],
        "intro": "집에 있는 채소를 활용해 담백하게 끓이는 된장찌개.",
        "steps": ["멸치육수를 끓인다", "감자·애호박·양파를 넣고 끓인다", "된장을 풀고 두부·대파를 넣어 마무리한다"],
        "tags": ["#된장", "#든든한국", "#집밥"],
        "rich": ["protein", "fiber"],
    },
    {
        "index": 3, "title": "김치볶음밥", "type": "밥/죽/떡",
        "situation": "일상", "ingredient_tag": "곡류", "method": "볶기",
        "url": "https://www.10000recipe.com/recipe/list?q=김치볶음밥",
        "views": 1200, "chef": "목업셰프", "servings": 1, "cook_time": 15, "difficulty": "아무나",
        "ingredients": [
            {"name": "밥", "amount": "1공기"}, {"name": "김치", "amount": "100g"},
            {"name": "계란", "amount": "1개"}, {"name": "대파", "amount": "1/2대"},
            {"name": "참기름", "amount": "1작은술"}, {"name": "간장", "amount": "1큰술"},
        ],
        "intro": "5분이면 완성되는 초간단 한끼. 김치가 살짝 익었을 때가 제일 맛있습니다.",
        "steps": ["김치를 참기름에 볶는다", "밥을 넣고 볶는다", "간장으로 간하고 계란후라이를 얹는다"],
        "tags": ["#간단요리", "#한끼", "#김치"],
        "rich": ["carbs", "fiber"],
    },
    {
        "index": 4, "title": "계란볶음밥", "type": "밥/죽/떡",
        "situation": "일상", "ingredient_tag": "곡류", "method": "볶기",
        "url": "https://www.10000recipe.com/recipe/list?q=계란볶음밥",
        "views": 900, "chef": "목업셰프", "servings": 1, "cook_time": 10, "difficulty": "아무나",
        "ingredients": [
            {"name": "밥", "amount": "1공기"}, {"name": "계란", "amount": "2개"},
            {"name": "양파", "amount": "1/4개"}, {"name": "당근", "amount": "1/4개"},
            {"name": "대파", "amount": "1/2대"}, {"name": "참기름", "amount": "1작은술"},
        ],
        "intro": "냉장고에 계란과 채소만 있어도 만들 수 있는 기본 볶음밥.",
        "steps": ["채소를 다져 볶는다", "밥을 넣고 볶다가 풀어둔 계란을 넣는다", "소금으로 간한다"],
        "tags": ["#간단요리", "#계란", "#아침대용"],
        "rich": ["protein", "carbs"],
    },
    {
        "index": 5, "title": "김치전", "type": "메인반찬",
        "situation": "야식", "ingredient_tag": "채소류", "method": "부치기",
        "url": "https://www.10000recipe.com/recipe/list?q=김치전",
        "views": 760, "chef": "목업셰프", "servings": 2, "cook_time": 15, "difficulty": "초급",
        "ingredients": [
            {"name": "김치", "amount": "150g"}, {"name": "밀가루", "amount": "1/2컵"},
            {"name": "계란", "amount": "1개"}, {"name": "대파", "amount": "1/2대"},
        ],
        "intro": "시원하게 익은 김치가 있으면 부침가루 없이도 전이 됩니다.",
        "steps": ["김치를 잘게 썰어 밀가루·계란과 반죽한다", "팬에 넉넉히 부어 중약불로 부친다", "앞뒤로 노릇하게 부친다"],
        "tags": ["#전", "#야식", "#김치"],
        "rich": ["fiber"],
    },
    {
        "index": 6, "title": "계란찜", "type": "메인반찬",
        "situation": "일상", "ingredient_tag": "계란", "method": "찌기",
        "url": "https://www.10000recipe.com/recipe/list?q=계란찜",
        "views": 690, "chef": "목업셰프", "servings": 2, "cook_time": 15, "difficulty": "초급",
        "ingredients": [
            {"name": "계란", "amount": "3개"}, {"name": "대파", "amount": "1/2대"},
            {"name": "소금", "amount": "약간"}, {"name": "참기름", "amount": "1작은술"},
        ],
        "intro": "부드러운 단백질 보충용 반찬. 아이들도 좋아합니다.",
        "steps": ["계란을 풀고 물 1:1로 섞는다", "소금으로 간해 그릇에 담는다", "중약불 10분간 뚜껑을 열고 쪄낸다"],
        "tags": ["#계란", "#부드러운반찬", "#단백질"],
        "rich": ["protein", "vitA"],
    },
    {
        "index": 7, "title": "시금치나물", "type": "밑반찬",
        "situation": "일상", "ingredient_tag": "채소류", "method": "무침",
        "url": "https://www.10000recipe.com/recipe/list?q=시금치나물",
        "views": 520, "chef": "목업셰프", "servings": 2, "cook_time": 10, "difficulty": "아무나",
        "ingredients": [
            {"name": "시금치", "amount": "200g"}, {"name": "마늘", "amount": "1작은술"},
            {"name": "간장", "amount": "1큰술"}, {"name": "참기름", "amount": "1작은술"},
        ],
        "intro": "철분과 식이섬유가 풍부한 기본 나물 반찬.",
        "steps": ["시금치를 데쳐 찬물에 헹꼈다", "물기를 짜고 양념에 무친다"],
        "tags": ["#나물", "#철분", "#건강반찬"],
        "rich": ["iron", "vitA", "fiber"],
    },
    {
        "index": 8, "title": "오이무침", "type": "밑반찬",
        "situation": "일상", "ingredient_tag": "채소류", "method": "무침",
        "url": "https://www.10000recipe.com/recipe/list?q=오이무침",
        "views": 430, "chef": "목업셰프", "servings": 2, "cook_time": 5, "difficulty": "아무나",
        "ingredients": [
            {"name": "오이", "amount": "1개"}, {"name": "고춧가루", "amount": "1큰술"},
            {"name": "식초", "amount": "1큰술"}, {"name": "설탕", "amount": "1작은술"},
            {"name": "마늘", "amount": "1작은술"},
        ],
        "intro": "5분 무침으로 아삭하게! 입맛 돋우는 반찬.",
        "steps": ["오이를 어슷하게 썬다", "양념과 버무린다"],
        "tags": ["#무침", "#아삭", "#여름반찬"],
        "rich": ["vitC", "fiber"],
    },
    {
        "index": 9, "title": "감자조림", "type": "메인반찬",
        "situation": "일상", "ingredient_tag": "채소류", "method": "조리기",
        "url": "https://www.10000recipe.com/recipe/list?q=감자조림",
        "views": 610, "chef": "목업셰프", "servings": 3, "cook_time": 25, "difficulty": "초급",
        "ingredients": [
            {"name": "감자", "amount": "3개"}, {"name": "간장", "amount": "3큰술"},
            {"name": "설탕", "amount": "1큰술"}, {"name": "마늘", "amount": "1작은술"},
            {"name": "참기름", "amount": "1작은술"},
        ],
        "intro": "간장 감자조림은 금방 식어도 맛있는 밥도둑 반찬.",
        "steps": ["감자를 도톰하게 썰어 볶는다", "간장·설탕·물을 넣어 조린다", "불을 올려 윤기를 낸다"],
        "tags": ["#조림", "#간장", "#감자"],
        "rich": ["carbs", "fiber"],
    },
    {
        "index": 10, "title": "어묵국", "type": "국/탕",
        "situation": "일상", "ingredient_tag": "해물류", "method": "끓이기",
        "url": "https://www.10000recipe.com/recipe/list?q=어묵국",
        "views": 540, "chef": "목업셰프", "servings": 2, "cook_time": 15, "difficulty": "아무나",
        "ingredients": [
            {"name": "어묵", "amount": "2장"}, {"name": "대파", "amount": "1/2대"},
            {"name": "마늘", "amount": "1작은술"}, {"name": "간장", "amount": "1큰술"},
        ],
        "intro": "동네 어묵 사옥에서 사 온 어묵으로 끓이는 따뜻한 국.",
        "steps": ["어묵을 썰어 볶다가 물을 붓는다", "간장·마늘로 간한다", "대파를 넣고 마무리"],
        "tags": ["#국", "#어묵", "#간식"],
        "rich": ["protein"],
    },
    {
        "index": 11, "title": "카레라이스", "type": "퓨전",
        "situation": "일상", "ingredient_tag": "곡류", "method": "볶기",
        "url": "https://www.10000recipe.com/recipe/list?q=카레라이스",
        "views": 830, "chef": "목업셰프", "servings": 2, "cook_time": 30, "difficulty": "초급",
        "ingredients": [
            {"name": "밥", "amount": "2공기"}, {"name": "감자", "amount": "1개"},
            {"name": "당근", "amount": "1/2개"}, {"name": "양파", "amount": "1/2개"},
            {"name": "소고기", "amount": "100g"}, {"name": "카레가루", "amount": "1/2봉"},
        ],
        "intro": "감자·당근·양파만 있으면 되는 국민 요리.",
        "steps": ["고기를 볶고 채소를 넣어 볶는다", "물 500ml를 붓고 끓인다", "카레가루를 풀어 걸쭉하게"],
        "tags": ["#카레", "#일품요리", "#한끼"],
        "rich": ["carbs", "fiber"],
    },
    {
        "index": 12, "title": "토마토달걀볶음", "type": "양식",
        "situation": "일상", "ingredient_tag": "계란", "method": "볶기",
        "url": "https://www.10000recipe.com/recipe/list?q=토마토달걀볶음",
        "views": 470, "chef": "목업셰프", "servings": 2, "cook_time": 15, "difficulty": "아무나",
        "ingredients": [
            {"name": "토마토", "amount": "2개"}, {"name": "계란", "amount": "3개"},
            {"name": "대파", "amount": "1/2대"}, {"name": "설탕", "amount": "1작은술"},
        ],
        "intro": "중국식 토마토 계란 볶음. 비타민C와 단백질을 한 접시에.",
        "steps": ["계란을 스크램블로 먼저 볶는다", "토마토를 넣어 물기를 내며 볶는다", "계란을 돌려 섞고 간한다"],
        "tags": ["#토마토", "#비타민", "#양식"],
        "rich": ["vitC", "vitA", "protein"],
    },
    {
        "index": 13, "title": "미역국", "type": "국/탕",
        "situation": "일상", "ingredient_tag": "해물류", "method": "끓이기",
        "url": "https://www.10000recipe.com/recipe/list?q=미역국",
        "views": 700, "chef": "목업셰프", "servings": 2, "cook_time": 25, "difficulty": "초급",
        "ingredients": [
            {"name": "미역", "amount": "30g"}, {"name": "소고기", "amount": "80g"},
            {"name": "마늘", "amount": "1작은술"}, {"name": "간장", "amount": "1큰술"},
            {"name": "참기름", "amount": "1작은술"},
        ],
        "intro": "칼슘·철분이 풍부해 산후조리 뿐 아니라 평소에도 좋은 국.",
        "steps": ["소고기를 참기름에 볶는다", "불린 미역과 간장을 넣고 볶는다", "물을 붓고 15분 끓인다"],
        "tags": ["#미역국", "#칼슘", "#건강국"],
        "rich": ["calcium", "iron"],
    },
    {
        "index": 14, "title": "김밥", "type": "밥/죽/떡",
        "situation": "소풍", "ingredient_tag": "곡류", "method": "기타",
        "url": "https://www.10000recipe.com/recipe/list?q=김밥",
        "views": 650, "chef": "목업셰프", "servings": 4, "cook_time": 40, "difficulty": "중급",
        "ingredients": [
            {"name": "밥", "amount": "2공기"}, {"name": "김", "amount": "4장"},
            {"name": "당근", "amount": "1/2개"}, {"name": "오이", "amount": "1/2개"},
            {"name": "계란", "amount": "2개"}, {"name": "단무지", "amount": "4줄"},
            {"name": "참기름", "amount": "1큰술"},
        ],
        "intro": "냉장고에 있는 채소를 말아 도시락까지 해결.",
        "steps": ["당근·오이·계란지단을 준비한다", "밥에 참기름·소금으로 간한다", "김 위에 재료를 올리고 만다"],
        "tags": ["#김밥", "#도시락", "#간식"],
        "rich": ["carbs", "protein"],
    },
    {
        "index": 15, "title": "바나나우유스무디", "type": "디저트",
        "situation": "간식", "ingredient_tag": "유제품", "method": "기타",
        "url": "https://www.10000recipe.com/recipe/list?q=바나나우유스무디",
        "views": 380, "chef": "목업셰프", "servings": 1, "cook_time": 5, "difficulty": "아무나",
        "ingredients": [
            {"name": "바나나", "amount": "1개"}, {"name": "우유", "amount": "250ml"},
            {"name": "꿀", "amount": "1큰술"},
        ],
        "intro": "칼슘 보충 간식. 바나나가 갈색으로 되기 전에 사라지게 만드는 최고의 방법.",
        "steps": ["바나나를 잘라 갈아둔다", "우유·꿀과 함께 갈아 마신다"],
        "tags": ["#스무디", "#칼슘", "#간식"],
        "rich": ["calcium", "vitC"],
    },
]

# 재료별 영양소 (100g 기준 근사치): kcal, protein(g), fat(g), carbs(g),
# sodium(mg), calcium(mg), iron(mg), vitA(µg RAE), vitC(mg), fiber(g)
NUTRIENTS = {
    "계란":    {"kcal": 150, "protein": 12, "fat": 10, "carbs": 1,  "sodium": 130, "calcium": 55,  "iron": 1.4, "vitA": 120, "vitC": 0,   "fiber": 0},
    "우유":    {"kcal": 64,  "protein": 3.2, "fat": 3.6, "carbs": 5,  "sodium": 40,  "calcium": 113, "iron": 0.1, "vitA": 45,  "vitC": 1,   "fiber": 0},
    "김치":    {"kcal": 25,  "protein": 1.6, "fat": 0.5, "carbs": 3,  "sodium": 700, "calcium": 50,  "iron": 0.9, "vitA": 40,  "vitC": 15,  "fiber": 1.8},
    "두부":    {"kcal": 84,  "protein": 9.8, "fat": 4.5, "carbs": 1.6,"sodium": 5,   "calcium": 145, "iron": 1.6, "vitA": 0,   "vitC": 0,   "fiber": 0.5},
    "돼지고기": {"kcal": 330, "protein": 17, "fat": 28,  "carbs": 0,  "sodium": 55,  "calcium": 5,   "iron": 0.7, "vitA": 5,   "vitC": 0,   "fiber": 0},
    "소고기":  {"kcal": 220, "protein": 20, "fat": 14,  "carbs": 0,  "sodium": 50,  "calcium": 8,   "iron": 2.3, "vitA": 7,   "vitC": 0,   "fiber": 0},
    "닭고기":  {"kcal": 150, "protein": 22, "fat": 6,   "carbs": 0,  "sodium": 70,  "calcium": 9,   "iron": 0.8, "vitA": 10,  "vitC": 0,   "fiber": 0},
    "밥":      {"kcal": 130, "protein": 2.7, "fat": 0.3, "carbs": 30, "sodium": 1,   "calcium": 5,   "iron": 0.2, "vitA": 0,   "vitC": 0,   "fiber": 0.4},
    "김":      {"kcal": 340, "protein": 37, "fat": 2.5, "carbs": 40, "sodium": 700, "calcium": 280, "iron": 18,  "vitA": 380, "vitC": 5,   "fiber": 2},
    "시금치":  {"kcal": 22,  "protein": 3,   "fat": 0.3, "carbs": 3,  "sodium": 55,  "calcium": 100, "iron": 3.2, "vitA": 480, "vitC": 25,  "fiber": 2.5},
    "양파":    {"kcal": 34,  "protein": 1,   "fat": 0.2, "carbs": 8,  "sodium": 3,   "calcium": 20,  "iron": 0.3, "vitA": 0,   "vitC": 8,   "fiber": 1.5},
    "감자":    {"kcal": 90,  "protein": 2,   "fat": 0.1, "carbs": 20, "sodium": 3,   "calcium": 9,   "iron": 0.6, "vitA": 0,   "vitC": 15,  "fiber": 2.2},
    "당근":    {"kcal": 36,  "protein": 0.8, "fat": 0.2, "carbs": 8,  "sodium": 45,  "calcium": 35,  "iron": 0.6, "vitA": 690, "vitC": 7,   "fiber": 2.6},
    "애호박":  {"kcal": 20,  "protein": 1,   "fat": 0.2, "carbs": 4,  "sodium": 2,   "calcium": 15,  "iron": 0.4, "vitA": 20,  "vitC": 12,  "fiber": 1.2},
    "오이":    {"kcal": 13,  "protein": 0.6, "fat": 0.2, "carbs": 2.5,"sodium": 3,   "calcium": 15,  "iron": 0.3, "vitA": 25,  "vitC": 8,   "fiber": 0.7},
    "토마토":  {"kcal": 17,  "protein": 0.8, "fat": 0.2, "carbs": 3.5,"sodium": 3,   "calcium": 9,   "iron": 0.3, "vitA": 60,  "vitC": 20,  "fiber": 1.1},
    "바나나":  {"kcal": 93,  "protein": 1.2, "fat": 0.3, "carbs": 23, "sodium": 1,   "calcium": 6,   "iron": 0.3, "vitA": 8,   "vitC": 10,  "fiber": 2.4},
    "어묵":    {"kcal": 170, "protein": 11, "fat": 8,   "carbs": 14, "sodium": 750, "calcium": 30,  "iron": 0.6, "vitA": 15,  "vitC": 0,   "fiber": 0.3},
    "미역":    {"kcal": 11,  "protein": 1.6, "fat": 0.2, "carbs": 1,  "sodium": 250, "calcium": 130, "iron": 1.2, "vitA": 20,  "vitC": 1,   "fiber": 0.6},
    "멸치":    {"kcal": 130, "protein": 21, "fat": 4,   "carbs": 0,  "sodium": 900, "calcium": 790, "iron": 2.5, "vitA": 30,  "vitC": 0,   "fiber": 0},
    "고등어":  {"kcal": 220, "protein": 19, "fat": 15,  "carbs": 0,  "sodium": 90,  "calcium": 25,  "iron": 1.1, "vitA": 40,  "vitC": 0,   "fiber": 0},
    "치즈":    {"kcal": 330, "protein": 25, "fat": 25,  "carbs": 2,  "sodium": 700, "calcium": 650, "iron": 0.3, "vitA": 300, "vitC": 0,   "fiber": 0},
    "밀가루":  {"kcal": 350, "protein": 10, "fat": 1.5, "carbs": 73, "sodium": 2,   "calcium": 18,  "iron": 1.2, "vitA": 0,   "vitC": 0,   "fiber": 2.5},
    "카레가루": {"kcal": 380, "protein": 8,  "fat": 12,  "carbs": 58, "sodium": 1200,"calcium": 60,  "iron": 3,   "vitA": 50,  "vitC": 0,   "fiber": 8},
    "단무지":  {"kcal": 15,  "protein": 0.5, "fat": 0.1, "carbs": 3,  "sodium": 900, "calcium": 20,  "iron": 0.3, "vitA": 0,   "vitC": 0,   "fiber": 1},
    "고춧가루": {"kcal": 290, "protein": 14, "fat": 9,   "carbs": 40, "sodium": 100, "calcium": 90,  "iron": 6,   "vitA": 400, "vitC": 30,  "fiber": 25},
    "된장":    {"kcal": 90,  "protein": 7,   "fat": 2.5, "carbs": 11, "sodium": 3300,"calcium": 70,  "iron": 2,   "vitA": 10,  "vitC": 0,   "fiber": 3},
    "간장":    {"kcal": 40,  "protein": 6,   "fat": 0,   "carbs": 5,  "sodium": 6000,"calcium": 30,  "iron": 1.5, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "참기름":  {"kcal": 880, "protein": 0,   "fat": 100, "carbs": 0,  "sodium": 0,   "calcium": 0,   "iron": 0,   "vitA": 0,   "vitC": 0,   "fiber": 0},
    "설탕":    {"kcal": 385, "protein": 0,   "fat": 0,   "carbs": 100,"sodium": 0,   "calcium": 0,   "iron": 0,   "vitA": 0,   "vitC": 0,   "fiber": 0},
    "마늘":    {"kcal": 130, "protein": 5,   "fat": 0.2, "carbs": 28, "sodium": 10,  "calcium": 15,  "iron": 1.5, "vitA": 0,   "vitC": 20,  "fiber": 2.5},
    "대파":    {"kcal": 25,  "protein": 1.5, "fat": 0.3, "carbs": 6,  "sodium": 8,   "calcium": 40,  "iron": 0.8, "vitA": 90,  "vitC": 20,  "fiber": 2},
    "상추":    {"kcal": 12,  "protein": 1.1, "fat": 0.2, "carbs": 2,  "sodium": 5,   "calcium": 35,  "iron": 1,   "vitA": 300, "vitC": 10,  "fiber": 1.2},
    "버섯":    {"kcal": 25,  "protein": 3,   "fat": 0.3, "carbs": 4,  "sodium": 3,   "calcium": 3,   "iron": 0.5, "vitA": 0,   "vitC": 2,   "fiber": 2.5},
    "꿀":      {"kcal": 300, "protein": 0.2, "fat": 0,   "carbs": 78, "sodium": 3,   "calcium": 5,   "iron": 0.2, "vitA": 0,   "vitC": 1,   "fiber": 0},

    # --- 확장(2026-09): 실제 레시피 120건 빈도 상위 재료 보강 ---
    "소금":    {"kcal": 0,   "protein": 0,   "fat": 0,   "carbs": 0,  "sodium": 38700,"calcium": 24, "iron": 0.3, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "후추":    {"kcal": 251, "protein": 10,  "fat": 3.3, "carbs": 64, "sodium": 20,  "calcium": 443, "iron": 9.7, "vitA": 10,  "vitC": 0,   "fiber": 25},
    "물":      {"kcal": 0,   "protein": 0,   "fat": 0,   "carbs": 0,  "sodium": 0,   "calcium": 0,   "iron": 0,   "vitA": 0,   "vitC": 0,   "fiber": 0},
    "버터":    {"kcal": 717, "protein": 0.9, "fat": 81,  "carbs": 0.1,"sodium": 643, "calcium": 24,  "iron": 0,   "vitA": 680, "vitC": 0,   "fiber": 0},
    "고추장":  {"kcal": 165, "protein": 4.4, "fat": 1,   "carbs": 36, "sodium": 2200,"calcium": 30,  "iron": 1.5, "vitA": 30,  "vitC": 0,   "fiber": 4},
    "굴소스":  {"kcal": 105, "protein": 2,   "fat": 0.2, "carbs": 25, "sodium": 4800,"calcium": 15,  "iron": 0.5, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "깨":      {"kcal": 570, "protein": 17,  "fat": 50,  "carbs": 23, "sodium": 5,   "calcium": 975, "iron": 14.6,"vitA": 0,   "vitC": 0,   "fiber": 12},
    "물엿":    {"kcal": 250, "protein": 0.1, "fat": 0,   "carbs": 65, "sodium": 40,  "calcium": 5,   "iron": 0.1, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "식초":    {"kcal": 12,  "protein": 0,   "fat": 0,   "carbs": 0.6,"sodium": 5,   "calcium": 5,   "iron": 0.1, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "청양고추": {"kcal": 20, "protein": 1,   "fat": 0.2, "carbs": 4,  "sodium": 2,   "calcium": 10,  "iron": 0.5, "vitA": 40,  "vitC": 50,  "fiber": 1.5},
    "마요네즈": {"kcal": 680,"protein": 0.6, "fat": 70,  "carbs": 2,  "sodium": 600, "calcium": 10,  "iron": 0.1, "vitA": 30,  "vitC": 0,   "fiber": 0},
    "참치액":  {"kcal": 30,  "protein": 5,   "fat": 0.1, "carbs": 1,  "sodium": 6500,"calcium": 10,  "iron": 0.4, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "맛술":    {"kcal": 150, "protein": 0.2, "fat": 0,   "carbs": 38, "sodium": 5,   "calcium": 3,   "iron": 0.1, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "식빵":    {"kcal": 280, "protein": 8,   "fat": 3,   "carbs": 52, "sodium": 450, "calcium": 30,  "iron": 1.5, "vitA": 0,   "vitC": 0,   "fiber": 2.4},
    "양배추":  {"kcal": 25,  "protein": 1.3, "fat": 0.2, "carbs": 5,  "sodium": 7,   "calcium": 40,  "iron": 0.4, "vitA": 12,  "vitC": 30,  "fiber": 2.4},
    "새우":    {"kcal": 95,  "protein": 19,  "fat": 0.9, "carbs": 0.2,"sodium": 120, "calcium": 70,  "iron": 0.5, "vitA": 20,  "vitC": 0,   "fiber": 0},
    "올리브유": {"kcal": 884,"protein": 0,   "fat": 100, "carbs": 0,  "sodium": 2,   "calcium": 1,   "iron": 0.1, "vitA": 0,   "vitC": 0,   "fiber": 0},
    "케찹":    {"kcal": 100, "protein": 1.5, "fat": 0.1, "carbs": 25, "sodium": 1000,"calcium": 12,  "iron": 0.4, "vitA": 40,  "vitC": 2,   "fiber": 0.3},
    "옥수수":  {"kcal": 90,  "protein": 3.3, "fat": 1.4, "carbs": 20, "sodium": 1,   "calcium": 3,   "iron": 0.5, "vitA": 15,  "vitC": 6,   "fiber": 2.4},
    "파슬리":  {"kcal": 36,  "protein": 3,   "fat": 0.8, "carbs": 6,  "sodium": 34,  "calcium": 138, "iron": 6.2, "vitA": 421, "vitC": 125, "fiber": 3.3},
    "참치":    {"kcal": 130, "protein": 25,  "fat": 4,   "carbs": 0,  "sodium": 40,  "calcium": 10,  "iron": 1,   "vitA": 15,  "vitC": 0,   "fiber": 0},
    "베이컨":  {"kcal": 550, "protein": 18,  "fat": 55,  "carbs": 0,  "sodium": 1600,"calcium": 8,   "iron": 0.8, "vitA": 5,   "vitC": 0,   "fiber": 0},
    "또띠아":  {"kcal": 300, "protein": 9,   "fat": 6,   "carbs": 52, "sodium": 620, "calcium": 100, "iron": 2.5, "vitA": 0,   "vitC": 0,   "fiber": 3},
    "호두":    {"kcal": 650, "protein": 15,  "fat": 65,  "carbs": 14, "sodium": 2,   "calcium": 100, "iron": 2.9, "vitA": 3,   "vitC": 1,   "fiber": 6.7},
    "부침가루": {"kcal": 360,"protein": 7,   "fat": 2,   "carbs": 75, "sodium": 800, "calcium": 20,  "iron": 1,   "vitA": 0,   "vitC": 0,   "fiber": 2},
    "레몬즙":  {"kcal": 22,  "protein": 0.3, "fat": 0.2, "carbs": 7,  "sodium": 1,   "calcium": 8,   "iron": 0.2, "vitA": 1,   "vitC": 30,  "fiber": 0.2},
    "들기름":  {"kcal": 884, "protein": 0,   "fat": 100, "carbs": 0,  "sodium": 0,   "calcium": 0,   "iron": 0,   "vitA": 0,   "vitC": 0,   "fiber": 0},
    "무":      {"kcal": 13,  "protein": 0.7, "fat": 0.2, "carbs": 2.6,"sodium": 13,  "calcium": 25,  "iron": 0.3, "vitA": 0,   "vitC": 14,  "fiber": 1.4},
    "블루베리": {"kcal": 57, "protein": 0.7, "fat": 0.3, "carbs": 14, "sodium": 1,   "calcium": 6,   "iron": 0.3, "vitA": 3,   "vitC": 9,   "fiber": 2.4},
    "딸기":    {"kcal": 30,  "protein": 0.9, "fat": 0.2, "carbs": 7,  "sodium": 1,   "calcium": 16,  "iron": 0.4, "vitA": 5,   "vitC": 60,  "fiber": 1.6},
    "숙주나물": {"kcal": 30, "protein": 2.8, "fat": 0.2, "carbs": 5,  "sodium": 5,   "calcium": 15,  "iron": 0.9, "vitA": 1,   "vitC": 10,  "fiber": 1.2},
    "콩나물":  {"kcal": 15,  "protein": 1.8, "fat": 0.2, "carbs": 2.3,"sodium": 5,   "calcium": 20,  "iron": 0.8, "vitA": 1,   "vitC": 8,   "fiber": 1.2},
    "햄":      {"kcal": 250, "protein": 12,  "fat": 20,  "carbs": 5,  "sodium": 1100,"calcium": 8,   "iron": 0.8, "vitA": 5,   "vitC": 0,   "fiber": 0},
    "베이킹파우더": {"kcal": 53, "protein": 0, "fat": 0, "carbs": 26, "sodium": 10600,"calcium": 460, "iron": 0.3, "vitA": 0, "vitC": 0, "fiber": 0},
    "면":      {"kcal": 280, "protein": 9,   "fat": 1.5, "carbs": 58, "sodium": 25,  "calcium": 12,  "iron": 1,   "vitA": 0,   "vitC": 0,   "fiber": 1.8},
}

# 성인 1일 권장 섭취량(목업용 대략치)
REFERENCE_INTAKE = {
    "kcal": 2100, "protein": 65, "fat": 55, "carbs": 310,
    "sodium": 2000, "calcium": 750, "iron": 12, "vitA": 700, "vitC": 100, "fiber": 25,
}

NUTRIENT_LABEL = {
    "kcal": "에너지", "protein": "단백질", "fat": "지방", "carbs": "탄수화물",
    "sodium": "나트륨", "calcium": "칼슘", "iron": "철분", "vitA": "비타민A",
    "vitC": "비타민C", "fiber": "식이섬유",
}
NUTRIENT_UNIT = {
    "kcal": "kcal", "protein": "g", "fat": "g", "carbs": "g",
    "sodium": "mg", "calcium": "mg", "iron": "mg", "vitA": "µg",
    "vitC": "mg", "fiber": "g",
}

# 부족 영양소별 보충 식품 힌트
DEFICIENCY_FOODS = {
    "protein": ["계란", "두부", "소고기", "닭고기"],
    "calcium": ["우유", "치즈", "미역", "멸치"],
    "iron": ["시금치", "소고기", "미역", "김"],
    "vitA": ["당근", "시금치", "계란", "김"],
    "vitC": ["토마토", "오이", "바나나", "상추"],
    "fiber": ["감자", "애호박", "김치", "바나나", "시금치"],
    "sodium": ["국물·김치·간장 양 줄이기"],
    "fat": ["고기·유제품 양 조절"],
    "kcal": ["식사 횟수·량 늘리기"],
    "carbs": ["밥·곡물 비율 점검"],
}

# ---------------------------------------------------------------- 알레르기
# 알레르기 카탈로그: 레시피 재료명(정규화)과 양방향 부분 일치로 판정한다.
# 키워드는 실제 레시피 CSV에 등장하는 재료명 변형을 커버하되,
# 간장·고추장 등 극미량만 쓰이는 가공 양념은 제외 대상에서 뺐다(추천이 전부 비어버림).
# not_with: 특정 키워드가 다른 알레르기 재료와 결합한 합성물일 때 오탐을 막는 가드
#   (예: "땅콩버터"는 유제품 버터가 아님)
ALLERGENS = [
    {"key": "egg", "label": "계란(달걀)",
     "keywords": ["계란", "달걀", "메추리알", "노른자", "난자", "마요네즈"]},
    {"key": "milk", "label": "우유·유제품",
     "keywords": ["우유", "치즈", "버터", "크림", "요거트", "요구르트", "요플레",
                  "아이스크림", "연유", "마가린", "밀키스"],
     "not_with": {"버터": ["땅콩"]}},
    {"key": "wheat", "label": "밀가루(글루텐)",
     "keywords": ["밀가루", "부침가루", "튀김가루", "빵", "빵가루", "면", "국수",
                  "소면", "우동", "파스타", "푸실리", "펜네", "마카로니", "스파게티",
                  "라면", "쫄면", "만두", "핫케이크", "호떡", "오레오", "웨하스"]},
    {"key": "soy", "label": "대두·콩",
     "keywords": ["대두", "콩", "두부", "두유", "콩국", "된장", "청국장", "낫토",
                  "미숫가루"],
     "not_with": {"콩": ["땅콩"]}},  # 땅콩은 콩(대두)과 다른 알레르기 항목
    {"key": "fish", "label": "생선",
     "keywords": ["생선", "고등어", "갈치", "삼치", "멸치", "꽁치", "연어", "참치",
                  "명태", "동태", "대구", "가자미", "장어", "정어리", "도미", "광어",
                  "아귀", "홍어", "황태", "명란", "액젓"]},
    {"key": "seafood", "label": "해산물(새우·게·조개)",
     "keywords": ["해물", "해산물", "새우", "게", "꽃게", "크랩", "조개", "굴",
                  "홍합", "바지락", "꼬막", "전복", "가리비", "오징어", "낙지",
                  "문어", "맛살", "크래미", "크레미", "멍게", "랍스터"]},
    {"key": "chicken", "label": "닭고기", "keywords": ["닭", "치킨"]},
    {"key": "pork", "label": "돼지고기",
     "keywords": ["돼지", "삼겹", "베이컨", "햄", "소시지", "비엔나", "스팸",
                  "목살", "앞다리"]},
    {"key": "beef", "label": "소고기",
     "keywords": ["소고기", "쇠고기", "차돌", "불고기", "스테이크", "다짐육",
                  "우삼겹", "안심", "등심", "갈비"]},
    {"key": "peanut", "label": "땅콩", "keywords": ["땅콩"]},
    {"key": "nuts", "label": "견과류",
     "keywords": ["견과", "호두", "잣", "아몬드", "캐슈", "피스타치오", "마카다미아"]},
    {"key": "sesame", "label": "참깨·들깨", "keywords": ["깨"]},
    {"key": "buckwheat", "label": "메밀", "keywords": ["메밀"]},
    {"key": "tomato", "label": "토마토",
     "keywords": ["토마토", "케찹", "캐첩", "캐찹", "파스타소스", "스파게티소스"]},
    {"key": "peach", "label": "복숭아", "keywords": ["복숭아"]},
]
